### ISSUE TITLE
repeat line

### ISSUE THREAD

**Issue by nikitabelonogov** [Lungesoft/Mail.ru-News-Search-Service-Lucene-6.2.0-WithOwnSearchBOT#1]
same line two times

[`exceptions.add("https://news.mail.ru/politics/");`](https://github.com/Lungesoft/Mail.ru-News-Search-Service-Lucene-6.2.0-WithOwnSearchBOT/blob/master/src/main/java/com/lungesoft/larch/SearchRobot.java#L28)

**Comment by nikitabelonogov** [comment]
pls fix

**Comment by Lungesoft** [comment]
Thanks for your feedback. I'll fix it in nearest update.
